# Generated by Django 3.1.7 on 2021-03-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210301_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
