# Generated by Django 3.1.7 on 2021-03-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_media_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='media',
            field=models.ManyToManyField(null=True, to='manager.Media'),
        ),
    ]
