# Generated by Django 3.1.7 on 2021-03-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20210301_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('artists', models.ManyToManyField(to='manager.Artist')),
                ('media', models.ManyToManyField(to='manager.Media')),
            ],
        ),
    ]
