# Generated by Django 3.1.7 on 2021-03-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20210305_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='media',
            field=models.ManyToManyField(to='manager.Media'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='tags',
            field=models.ManyToManyField(to='manager.Tag'),
        ),
    ]
