# Generated by Django 3.1.7 on 2021-03-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20210305_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='duration_active',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
