# Generated by Django 3.1.7 on 2021-03-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_media_file_extension'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist',
            new_name='Person',
        ),
        migrations.RemoveField(
            model_name='recordingsession',
            name='artists',
        ),
        migrations.AddField(
            model_name='recordingsession',
            name='personnel',
            field=models.ManyToManyField(blank=True, to='manager.Person'),
        ),
    ]
