# Generated by Django 3.1.7 on 2021-03-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20210328_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='related_media',
            field=models.ManyToManyField(blank=True, related_name='_media_related_media_+', to='manager.Media'),
        ),
    ]
