# Generated by Django 3.1.7 on 2021-03-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_auto_20210328_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='file_extension',
        ),
    ]
