# Generated by Django 3.1.7 on 2021-03-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_auto_20210328_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='duration_active',
        ),
    ]
