# Generated by Django 3.1.7 on 2021-03-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_remove_person_duration_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicallocation',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='uploads/locations/'),
        ),
    ]
